### ISSUE TITLE
module 'cv2.cv2' has no attribute 'xfeatures2d'

### ISSUE THREAD

**Issue by patel999jay** [shortstheory/RGBD-Tracking#1]
Hi,

Do you use something special for this function ? I am getting following error which i guess because of `SIFT` function.
Can you please update the requirements for this ? may be newer version of cv2 obsolete those function.

Here is the error I had while running demo file. I had double check my cv2 package successfully imported.

```bash
Traceback (most recent call last):
  File "demo.py", line 70, in <module>
    dt = DepthTracker(dl.K,particleN,particleCov,0.6,'sift')
  File "/home/jay/Documents/RGBD-Tracking/src/DepthTracker.py", line 28, in __init__
    self.vision = Vision(cameraK, detector)
  File "/home/jay/Documents/RGBD-Tracking/src/Vision.py", line 12, in __init__
    self.featureDetector = cv2.xfeatures2d.SIFT_create() # xfeatures2d.SIFT_create()
AttributeError: module 'cv2.cv2' has no attribute 'xfeatures2d'

jay@jay-MS-7885:~/Documents/RGBD-Tracking$ python3
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> 


```

**Comment by shortstheory** [comment]
Hi, you would need to downgrade to v3.4.17 or below of OpenCV for using SIFT features. I suggest doing so in a new virtualenv.

**Comment by patel999jay** [comment]
Awesome. I downgrade as you suggested and it worked. i was wondering is it possible to direct webcam feed to track 3D-object instead of using pre-processed data ?

**Comment by shortstheory** [comment]
I don't think a webcam would work for this as this project relies on using an RGBD camera feed from a kinect or an Intel realsense camera. It would also require a 2D bounding box detector such as TLD, CSRT, or Mobilenet as an input to work.
